title: <p align="center"> Richard Kanagaraj </p>
logo: /assets/img/my_picture.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/richard-samuel-88b2b819/">LinkedIn</a> |
  <a href="https://github.com/samrich76/">GitHub</a>
  
  <br>   
  I'm working on J2EE, Power BI,  Power App, Data Science, Big Data,  Machine learning
  Working in Globus Medical Inc for 17 years.
  <br>
  </p>



theme: jekyll-theme-minimal
